[package]
name = "uaf"
version = "0.1.0"
authors = ["RainWang6188 <3045465496@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"